### PR TITLE
Improve tSyntax regex extractor

### PR DESCRIPTION
**Pull request by pindab0ter**
It is not uncommon to have arguments and line breaks within `$t` style translation functions.

We use (an older version of) [Vue I18n](https://kazupon.github.io/vue-i18n/). My changes add support for common use cases while not impacting existing use cases.

I added a test for `__()` style calls with line breaks in the arguments, but did not do this for `$_` style as I am not familiar with those.

### CODE REVIEW

**Comment by Bottelet** [comment]
Hi @pindab0ter 

Thanks for the PR. 

I'm not sure I understand the `tc` in the regex. I completely agree with the line break; that makes a lot of sense.

**Comment by pindab0ter** [comment]
The `$tc` is used by [Vue I18n 8.x pluralization](https://kazupon.github.io/vue-i18n/guide/pluralization.html#accessing-the-number-via-the-pre-defined-argument). I figured adding `c?` doesn't hurt anything and you could argue that it is still a `$t`-style function.

**Comment by pindab0ter** [comment]
I turned the PR into a draft as I found cases where our translation function calls weren't closed correctly sometimes, resulting in malformed keys ending up in the translation file.

What is your philosophy? Garbage in = garbage out, or do you want to complicate the regex to guard against such cases?

**Comment by Bottelet** [comment]
> The `$tc` is used by [Vue I18n 8.x pluralization](https://kazupon.github.io/vue-i18n/guide/pluralization.html#accessing-the-number-via-the-pre-defined-argument). I figured adding `c?` doesn't hurt anything and you could argue that it is still a `$t`-style function.

Understood TIL :) 


> What is your philosophy? Garbage in = garbage out, or do you want to complicate the regex to guard against such cases?

Good question. So I think I wish to try and guard as much as possible, as that is what happens on the PHP end, for example, if a blade or really any PHP  file can't parse, it won't work, and throw an exception. 

There is also a case for just being able to throw anything at it, but for now it's simpler to "guard" aginst such cases.

**Comment by pindab0ter** [comment]
The PR is ready for review.

**Comment by Bottelet** [comment]
Thanks for the PR @pindab0ter

**Pull request merged**
